### PR TITLE
Updated SDL to 2.0.14

### PR DESCRIPTION
**Pull request by mrhelmut**
Hi there,

This is an update of SDL from 2.0.12 to 2.014

There are all built from source:
- Windows built with VS2019 toolchain with VC Runtime statically linked
- Linux built with clang 6 on Ubuntu 18.04 with wayland support
- macOS built on High Sierra with clang (this one has a High Sierra requirement, which is the same as ```dotnet```)

Tested working on all systems.

@harry-cpp @Jjagg

### CODE REVIEW

**Comment by Jjagg** [comment]
> macOS built on High Sierra with clang (this one has a High Sierra requirement, which is the same as dotnet)

We currently still target .NET Framework with DesktopGL. Any idea if it's worth keeping support for older mac versions?

**Comment by mrhelmut** [comment]
Let me check if I can work a backcompat with older macOS.

**Comment by Jjagg** [comment]
Not sure if you caught my edit. Our docs say we already have a High Sierra requirement, though I'm not sure what requires it.

**Comment by mrhelmut** [comment]
```dotnet``` 3.1+ does, it's a runtime requirement. I guess I wrote that part, and didn't have net452 in mind for that.

The question is: do we expect users to not use ```dotnet``` on macOS and instead use the old MonoKickstart (which would support older macOS)?

**Comment by Jjagg** [comment]
Deploying with MonoKickstart is a huge pain compared to the newer way, I wouldn't recommend it.

But 10% is quite a lot. I do think it'll be less than that for 'gamers', but the Steam survey does not help much because there's 7% unspecified OS version for macs: https://store.steampowered.com/hwsurvey?platform=mac.

Thoughts @harry-cpp @tomspilman

**Comment by harry-cpp** [comment]
We should not support any macOS versions which have already reached their end of life (aka. anything lower than High Sierra already reached its end of life).

**Comment by Jjagg** [comment]
Ah, in that case I agree. We shouldn't go out of our way to support EOL versions. And we already covered this in our docs, so no changes required there :)

**Comment by mrhelmut** [comment]
Ready when you are then. I'll bump the dependencies as well as the SDL controller DB.

**Pull request merged**
