### PR TITLE
Include both desktop and UWP assemblies where necessary

### PR DESCRIPTION
**Pull request by Jjagg**
Previously the assemblies targeting .NET Standard were used except for MediaFoundation, but there are other assemblies in which we need some parts that are conditionally compiled. I didn't properly research this when I upgraded the assemblies and just pulled in the .NET Standard ones. Sorry about that.

Specific assemblies we need are:

- SharpDX, to fix issue MonoGame/MonoGame#5998 and similar issues that may have come up otherwise for both desktop and UWP ([link](https://github.com/sharpdx/SharpDX/blob/8f03cb4ff8eaa2768b45857e3d4ca768a123932c/Source/SharpDX/Utilities.cs#L1042-L1108))
- SharpDX.XAudio2 for XAudio2.9 support on UWP ([link](https://github.com/sharpdx/SharpDX/blob/8f03cb4ff8eaa2768b45857e3d4ca768a123932c/Source/SharpDX.XAudio2/XAudio2.cs#L88-L117))

### CODE REVIEW

**Comment by Jjagg** [comment]
Don't merge yet, this needs some tweaking. I think it needs the .NET 4.0 assemblies instead of .NET 4.5 and we need the XInput desktop-specific assembly too (I overlooked this because it was fixed already in the develop branch of SharpDX).

It's worth noting that the next release of SharpDX will let use use the .NET Standard assemblies for XAudio and XInput thanks to @amerkoleci

**Comment by amerkoleci** [comment]
If you find that other assemblies need to be fixed for .net standard please open issue on SharpDX,  I will try to fix it

**Comment by tomspilman** [comment]
@Jjagg - So what is the status of this?  Does it fix the issues with Xbox One UWP?

**Comment by Jjagg** [comment]
Oh, sorry I completely lost track of this and haven't pulled the right dependencies as described in my last comment. Will fix this ASAP and tag you when it's done. Thanks for the heads-up!

**Comment by tomspilman** [comment]
@KonajuGames @dellis1972 @DDReaper - Can you guys review this?  I want to be sure we got things right this time.

**Comment by DDReaper** [comment]
Will this also affect the NuGet package dependencies @Jjagg ? do we need to select an alternate version.  Must admit, I've had no issues pushing and running those on UWP, either on windows or xbox.

**Comment by Jjagg** [comment]
I think for the NuGets the target is picked automatically when you pull in a lib, right? So e.g. UWP would always use the uap10.0 lib. Or do you actually need to specify the target? Assuming the former, nothing needs to be done and that would explain why NuGets work properly.

**Comment by tomspilman** [comment]
@Jjagg @DDReaper - This good to merge then?

**Comment by Jjagg** [comment]
@tomspilman Yes, this is good to go. But I'd like to mention again, that users will not be able to simply target .NET Framework 4.0 to run their game on Windows XP because we use .NET Standard 1.1 libs which require .NET Framework 4.5 or higher (4.5 is the default target for the MG DX template). 

If you'd like I can include all 4.0 assemblies from SharpDX so users can still easily target Windows XP if they want to.

**Comment by tomspilman** [comment]
> If you'd like I can include all 4.0 assemblies from SharpDX so users can still easily target Windows XP if they want to.

Windows XP is now 16 years old and there have been 4 new major versions of Windows released since then.  Not only that but less than 0.32% of Steam users are on XP...   not 32%...  but one third of one percent.

I think it is safe to not support Windows XP moving forward.  Especially since anyone that wants to can easily use an older version of SharpDX/MonoGame if they need to.

@KonajuGames @dellis1972 ?

**Comment by Jjagg** [comment]
If dropping XP support is fine, these PRs are good to go.

**Comment by DDReaper** [comment]
This works for me. As for dropping XP support, I am also fine with that as apart from Cash Machines, most users have moved off to at least Win7.

Plus MS no longer supports security fixes on that platform either.

**Comment by dellis1972** [comment]
The consensus seems to be for dropping XP. So I am merging.

**Pull request merged**
