### PR TITLE
Bump to SDL 2.0.12 for Linux and Windows

### PR DESCRIPTION
**Pull request by mrhelmut**
Hey there,

This a bump to SDL 2.0.12 for Linux and Windows. @harry-cpp is expected to push the macOS binary.

Details:
- Windows: built with VC++ 2019, runtime statically linked
- Linux: built with gcc on Ubuntu 16.04, with all backends enabled (inc. wayland)

It also removes x86 Linux, since this is no more supported as of .Net Core targets.

### CODE REVIEW

**Comment by harry-cpp** [comment]
This PR ready?

**Comment by mrhelmut** [comment]
Hold it on a sec, I sent the build to mac users to check if everything is fine.
I'll ping back once verified.

**Comment by harry-cpp** [comment]
You can also use me to test macOS builds btw. XD

**Comment by mrhelmut** [comment]
Ah true! I should get you an access at some point. :D

PR is good to go! Every systems tested.

**Pull request merged**
