### PR TITLE
Update SharpFont to Fix #5196

### PR DESCRIPTION
**Pull request by dellis1972**

### CODE REVIEW

**Comment by dellis1972** [comment]
Dont merge yet , work in progress.

**Comment by KonajuGames** [comment]
Does this statically link the runtime? And we don't need the 32-bit version
as our pipeline only supports running on 64-bit.

**Comment by dellis1972** [comment]
> Does this statically link the runtime? And we don't need the 32-bit version
as our pipeline only supports running on 64-bit.

not sure what you mean by static linking? its just a .net dll update and a slight change to the dll.config files. I updated the 32bit ones just for parity

**Comment by dellis1972** [comment]
@KonajuGames it should be ok to go, but I want to fork https://github.com/Robmaister/SharpFont as I did make some changes which we need. Mostly because they moved to use PCL and using the PCL completely messes up our system because it pulls in stuff like `System.Drawing.Primitives` which cause build failures. So we need to custom build for .net 4.5.

**Comment by KonajuGames** [comment]
Merged.

**Pull request merged**
