### PR TITLE
GLSLOptimizerSharp

### PR DESCRIPTION
**Pull request by Jjagg**
Add GLSLOptimizerSharp stuff for MonoGame/MonoGame#5354

### CODE REVIEW

**Comment by KonajuGames** [comment]
Is the source going to be included for the GLSLOptimizer.dll?

**Comment by Jjagg** [comment]
You mean like add it as a submodule?

**Comment by KonajuGames** [comment]
Where is it built from?  Can anyone rebuild it easily in the future?

**Comment by Jjagg** [comment]
I built it from Deans repo over here: https://github.com/infinitespace-studios/GLSLOptimizerSharp

**Comment by KonajuGames** [comment]
I have now forked that repo into the MonoGame account.  So all is good.

**Comment by Jjagg** [comment]
I had to build the native .so from the original repo by wrapping the glsl_optimizer.h file in a "extern C" as done in [this PR](https://github.com/aras-p/glsl-optimizer/pull/135/files). Then I set the BUILD_SHARED_LIBS option in the CMakeLists file so it would produce a shared object rather than a static lib. Maybe we should also fork the original and apply these changes.

There's a bit of an inconsistency here in terms of version of the glsl_optimizer libs. Nothing breaking, but some minor bugfixes are only in the .so lib since I just compiled that. The dylib and dll were already in the GLSLOptimizerSharp repo so I just used those. Might be better to get those up to date too if only for consistency.

**Comment by KonajuGames** [comment]
Build the DLL and dylib from the same source so they are consistent. I can
fork the repo later and we can add the extern definition to it.

**Comment by Jjagg** [comment]
Will do that tomorrow. I'll squash the commits so the older binaries aren't kept in history, bloating the repo.

**Comment by Jjagg** [comment]
This needs the Mac dylib. Can anyone with a Mac give a hand here? 

We need a build of https://github.com/aras-p/glsl-optimizer. There are XCode project files in the repo. You probably need to change the application type from static to dynamic (I had to for Windows and Linux). Then just build it to get a dylib.

**Comment by KonajuGames** [comment]
@Jjagg Try this [dylib](https://www.dropbox.com/s/qzrm68pdj5kc155/libglsl_optimizer.dylib?dl=0).

**Comment by KonajuGames** [comment]
Merging.

**Pull request merged**
