### PR TITLE
Rebase replaceopentk branch to the master

### PR DESCRIPTION
**Pull request by cra0zy**
Needed so https://github.com/mono/MonoGame/pull/4554 can also be rebased.

### CODE REVIEW

**Comment by mrhelmut** [comment]
With this rebase, I'll try to take a look at the OpenAL stuff.

**Comment by tomspilman** [comment]
Ok.... merged!

**Comment by cra0zy** [comment]
@tomspilman In order for https://github.com/mono/MonoGame/pull/4554 to be mergable you have to do one of 2 things:

1) Rebase replace_opentk branch to develop
```
git checkout replace_opentk
git rebase origin/develop
fix stuff
git rebase --continue
* last 2 thing will need to be repeated several times
```

2) Delete replace_opentk branch and use my changes for it
```
git checkout develop
git branch -D replace_opentk
git push origin --delete replace_opentk
git remote add crazy https://github.com/cra0zy/MonoGame.git
git checkout crazy/SDL2Win
git branch replace_opentk
git push -u origin replace_opentk
```

The SDL2Win branch is updated with everything: https://github.com/cra0zy/MonoGame/tree/SDL2Win

Side note, maybe we should use my fork for replace_opentk... I am doing most of the job anyway and it's gonna be easier for me to keep it maintained. Later once it's done we submit it back to develop like in the original plan.

**Comment by tomspilman** [comment]
We will need to work this out with @dellis1972 and anyone else working on the SDL2 path.  As long as they are good with it then I am.

**Comment by dellis1972** [comment]
@cra0zy @tomspilman  I am working on ripping out all of the OpenGL/AL calls from OpenTK to our own binding. Its a large job. I haven't pushed anything yet so we can rebase without a problem. I

**Comment by cra0zy** [comment]
@mrhelmut https://github.com/mono/MonoGame/issues/4399#issuecomment-186669458

**Comment by mrhelmut** [comment]
Just read that. :+1:

**Comment by cra0zy** [comment]
:D

**Pull request merged**
