### PR TITLE
Add Eto.Forms dlls

### PR DESCRIPTION
**Pull request by cra0zy**
- name: Eto.Forms
 - version: 2.2.0
 - acquired from: NuGet packages
   - https://www.nuget.org/packages/Eto.Forms/
   - https://www.nuget.org/packages/Eto.Platform.Gtk/
   - https://www.nuget.org/packages/Eto.Platform.Gtk3/
   - https://www.nuget.org/packages/Eto.Platform.Windows/

@tomspilman @KonajuGames We should make a PR template from what I did above (https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/)

### CODE REVIEW

**Comment by tomspilman** [comment]
Note...  this is the sort of headaches I feel we avoid by not making out builds depend on NuGet:

http://arstechnica.com/information-technology/2016/03/rage-quit-coder-unpublished-17-lines-of-javascript-and-broke-the-internet/

**Comment by tomspilman** [comment]
> We should make a PR template from what I did above 

I'll make a note of that...  I wanted to experiment with adding these too.

**Comment by cra0zy** [comment]
> Note... this is the sort of headaches I feel we avoid by not making out builds depend on NuGet:

I just took out dlls from NuGet, I didn't add nuget packages.

**Comment by tomspilman** [comment]
> I just took out dlls from nuget packages, I didn't add nuget packages themselves.

I know...  it just reminded me of that recent mess in the JavaScript community.

**Pull request merged**
