### PR TITLE
Added JSIL dll file

### PR DESCRIPTION
**Pull request by cra0zy**
Build from source code using: https://github.com/sq/JSIL/tree/eb73ec10fe0a85b7b3ed7d027c3d61311719d19a

### CODE REVIEW

**Comment by tomspilman** [comment]
I know what JSIL is...  but remind me what this DLL is used for? Is this used for JavaScript generation?

**Comment by cra0zy** [comment]
> Is this used for JavaScript generation?

Kind of.

It's used to call javascript from c# when compiled with JSILc. ie:
https://github.com/cra0zy/MonoGame/blob/webstuff/MonoGame.Framework/Web/WebGameWindow.cs#L7
https://github.com/cra0zy/MonoGame/blob/webstuff/MonoGame.Framework/Web/WebGameWindow.cs#L34

**Comment by tomspilman** [comment]
> It's used to call javascript from c# when compiled with JSIL. ie:

Right...  now I remember.  So we build a "web" platform version of MonoGame and stuff.  It internally uses this assembly to generate/call JS features.  However this C# assembly is never actually run...  it is instead used by the JSIL tools for generating the actual JS version of MonoGame.

**Comment by cra0zy** [comment]
> Right... now I remember. So we build a "web" platform version of MonoGame and stuff. It internally uses this assembly to generate/call JS features. However this C# assembly is never actually run... it is instead used by the JSIL tools for generating the actual JS version of MonoGame.

Yup

**Pull request closed without merging**
